services:
  attelier:
    build: .
    image: attelier-backend:latest
    container_name: attelier_backend

    ports:
      - "2736:2736"

    networks:
      home-tail:
        ipv4_address: 172.20.0.10

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  home-tail:
    external: true