services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_universal
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      home-tail:
        ipv4_address: 172.20.0.11

volumes:
  pgdata:

networks:
  home-tail:
    external: true
