services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared

    restart: unless-stopped

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      - homelab

networks:
  homelab:
    external: true